{{config(materialized='view', enabled=true, tags='raw')}}

select
    b.O_ORDERKEY as ORDER_ID,
    b.O_CUSTKEY as CUSTOMER_ID,
    b.O_ORDERDATE as ORDER_DATE,
    DATEADD(DAY, 20, b.O_ORDERDATE) AS TRANSACTION_DATE,
    TO_NUMBER(RPAD(CONCAT(b.O_ORDERKEY, b.O_CUSTKEY, TO_CHAR(b.O_ORDERDATE, 'YYYYMMDD')),  24, '0')) AS TRANSACTION_NUMBER,
    b.O_TOTALPRICE as AMOUNT,
    CAST(
    CASE ABS(MOD(RANDOM(1), 2)) + 1
        WHEN 1 THEN 'DR'
        WHEN 2 THEN 'CR'
    END AS VARCHAR(2)) AS TYPE
from SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.ORDERS as b
left join SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.CUSTOMER as c on b.O_CUSTKEY = c.C_CUSTKEY
where b.O_ORDERDATE = {{var("date")}}