version: 2

sources:
  - name: RAW
    database: DV_PROTOTYPE_DB
    schema: DEMO_RAW
    tables:
      - name: raw_orders
      - name: raw_inventory
      - name: raw_transactions
  - name: STG
    database: DV_PROTOTYPE_DB
    schema: DEMO_STG
    tables:
      - name: stg_orders
        identifier: v_stg_orders
      - name: stg_inventory
        identifier: v_stg_inventory
      - name: stg_transactions
        identifier: v_stg_transactions